# common provisioning tasks for docker compose

- name: docker-install
  # installs the script
  #
  # examples from the docker team install this in /usr/local/bin but that's inconvenient and frankly
  # if FHS justifies installing docker in /bin, it should also justify installing docker-compose there too;
  # the only reason that doesn't happen is because docker as a project doesn't do as much as it could for
  # supporting tidy ecosystems, so for in-house use it would be smart to build your own RPMs to do the right thing
  shell: curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /bin/docker-compose && chmod +x /bin/docker-compose
